name: Check PR title
permissions: read-all
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-PR
  cancel-in-progress: true
jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: satvik-s/pr-title-check@1.3.0
        with:
          pattern: '^((build|chore|merge|ci|docs|feat|fix|major|perf|refactor|style|test)(\(.*\))?:( DNSF-\d{4})? [A-Z].*)$'